on:
push:
branches: [ &quot;main&quot; ]

jobs:
demo:
runs-on:ubuntu-latest

steps:
-name:Checkoutrepository
uses:actions/checkout@v4

-name:Accesssecretvalue
run:echo&quot;The secret key is ${{ secrets.MY_SECRET_KEY }}&quot;
